// website/scripts/gen-license-keypair.ts
//
// One-shot generator for the RS256 license keypair. Produces:
//
//   * Private key  PEM written to ./tmp/license-private.pem; user copies
//     it into website/.env as LICENSE_PRIVATE_KEY (single line, escaped \n).
//   * Public key   PEM written into sharedUI/src/lib/license-pubkey.ts as a
//     committed constant; bundled with every extension at build time.
//
// Run:
//   npm run license:gen        (from website/)
//
// Rotation: re-running invalidates ALL existing licenses (clients will
// fail to verify and fall back to live website auth). Plan rotations
// during low-traffic windows and budget for users to re-auth.

import { generateKeyPairSync } from "node:crypto";
import { mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";


const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..", "..");


function main(): void {
  const { privateKey, publicKey } = generateKeyPairSync("rsa", {
    modulusLength: 2048,
    publicKeyEncoding:  { type: "spki",  format: "pem" },
    privateKeyEncoding: { type: "pkcs8", format: "pem" },
  });

  //  Private key  drop in tmp/ so the user copies it manually.
  const tmpDir = join(REPO_ROOT, "website", "tmp");
  mkdirSync(tmpDir, { recursive: true });
  const privateOut = join(tmpDir, "license-private.pem");
  writeFileSync(privateOut, privateKey, { encoding: "utf-8", mode: 0o600 });

  //  Public key  baked into the committed sharedUI bundle.
  const pubFile = join(REPO_ROOT, "sharedUI", "src", "lib", "license-pubkey.ts");
  const pubContent = `// sharedUI/src/lib/license-pubkey.ts
//
// AUTO-GENERATED by website/scripts/gen-license-keypair.ts.
// Public half of the JaPa license-signing keypair. Safe to commit  the
// matching private key lives only in the website's LICENSE_PRIVATE_KEY env.
//
// Every extension, the CLI, and the Flask backend bundle this constant so
// they can verify license JWTs offline. Re-run the generator to rotate.

export const LICENSE_PUBLIC_KEY = ${JSON.stringify(publicKey)};

export const LICENSE_KEY_ALGORITHM = "RS256" as const;
`;
  writeFileSync(pubFile, pubContent, { encoding: "utf-8" });

  //  Friendly summary.
  console.log("");
  console.log("  License keypair generated.");
  console.log("");
  console.log("  Private key written to:");
  console.log(`    ${privateOut}`);
  console.log("");
  console.log("  Next steps:");
  console.log("    1. Add LICENSE_PRIVATE_KEY to website/.env. Single line, \\n-escaped:");
  console.log("       LICENSE_PRIVATE_KEY=\"-----BEGIN PRIVATE KEY-----\\n...\\n-----END PRIVATE KEY-----\\n\"");
  console.log("");
  console.log("    2. Remove tmp/license-private.pem (the .env value is authoritative).");
  console.log("");
  console.log("  Public key embedded in: sharedUI/src/lib/license-pubkey.ts");
  console.log("  Verifies with: jose (browser/extension), jsonwebtoken (Node), PyJWT (Python).");
  console.log("");

  // Tiny dev convenience: print the .env-ready single line as well so
  // the user can paste without manual escaping.
  const oneLine = privateKey.replace(/\n/g, "\\n");
  const envFile = join(REPO_ROOT, "website", "tmp", "license-private.env.line");
  writeFileSync(envFile, `LICENSE_PRIVATE_KEY="${oneLine}"\n`, { encoding: "utf-8", mode: 0o600 });
  console.log(`  .env-ready snippet: ${envFile}`);
  console.log("");
}


// Run main() if executed directly (tsx invokes the module's top-level scope).
main();
